TypeChecker Done
2kodevs/cool-compiler-2020 pull request #2
Opened 2020-05-01 19:00 UTC by stdevRulo

Semantic errors verificator done.

It is important not to review only the TypeChecker visitor, it is also necessary a review for the grammar

Most important files:
-  CoolUtils.py
-  visitors.py

2020-05-01 21:01 UTC, AntiD2ta requested changes

2020-05-01 21:01 UTC, AntiD2ta commented on src/core/cmp/visitors.py
>      raise Exception('El LCA se partio')
```suggestion
```

2020-05-11 00:16 UTC, mauricio1802 approved these changes

2020-05-20 22:15 UTC, AntiD2ta approved these changes

2020-05-20 22:15 UTC, merged